spring:
  config:
    import: application-secret.yml

mybatis:
  mapper-locations:
    - /mappers/*.xml

user:
  profile:
    img:
     default: https://firebasestorage.googleapis.com/v0/b/userprofile-43e23.appspot.com/o/TeamProject%2F%ED%9D%90%EB%AD%87.PNG?alt=media&token=1fb1e5f5-f11a-4181-bdb0-1f52aab0565d
    thumbnailImg:
     default: https://firebasestorage.googleapis.com/v0/b/userprofile-43e23.appspot.com/o/TeamProject%2Frabbit.PNG?alt=media&token=0e797df1-9b1a-4748-8f08-2cf547b374f3


