spring:
  config:
    import: application-secret.yml

mybatis:
  mapper-locations:
    - /mappers/*.xml

user:
  profile:
    img:
     default: https://firebasestorage.googleapis.com/v0/b/userprofile-bc307.appspot.com/o/user%2Fdefault.png?alt=media&token=98467c2c-c4ef-4cd3-8ce1-e43e07faf5ad